### ISSUE TITLE
Not compatible with Neo 3.x

### ISSUE THREAD

**Issue by thisjustin** [maxdemarzi/neo_warmup#1]
When trying to run warmup with Neo 3.0.1 we get the following error message:

```
ERROR Failed to start Neo4j: Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-172a32a3@e95de3fa==org.neo4j.server.web.NeoServletContainer,-1,false Starting Neo4j failed: org.neo4
j.server.web.NeoServletContainer-172a32a3@e95de3fa==org.neo4j.server.web.NeoServletContainer,-1,false
org.neo4j.server.ServerStartupException: Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-172a32a3@e95de3fa==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:81)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:60)
        at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-172a32a3@e95de3fa==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:353)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:168)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:316)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:208)
        ... 3 more
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
```

**Comment by maxdemarzi** [comment]
You can make it compatible by changing the pom to use neo4j 3.0.1 instead of 2.3.x... BUT I suggest you start using APOC instead. See http://neo4j-contrib.github.io/neo4j-apoc-procedures/#_warmup

**Comment by thisjustin** [comment]
@maxdemarzi totally missed the warmup script when browsing APOC - thanks for the quick reply, we'll use that.
